# Generated by Django 5.0.12 on 2025-02-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='date',
        ),
        migrations.AddField(
            model_name='athlete',
            name='nationality',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='assists',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='goals',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
